// <auto-generated />
using System;
using ArxFlow.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArxFlow.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106221645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ArxFlow.Models.AnbimaTPF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoSelic")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Criterio")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataBase")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DesvioPadrao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IntervaloIndMaxD0")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IntervaloIndMaxD1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IntervaloIndMinD0")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IntervaloIndMinD1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PU")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxaCompra")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxaIndicativa")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxaVenda")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia")
                        .HasDatabaseName("IX_AnbimaTPF_DataReferencia");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("IX_AnbimaTPF_DataVencimento");

                    b.HasIndex("Titulo")
                        .HasDatabaseName("IX_AnbimaTPF_Titulo");

                    b.HasIndex("DataReferencia", "Titulo", "DataVencimento")
                        .IsUnique()
                        .HasDatabaseName("IX_AnbimaTPF_DataReferencia_Titulo_DataVencimento");

                    b.ToTable("AnbimaTPFs");
                });

            modelBuilder.Entity("ArxFlow.Models.AnbimaVNA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoSelic")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Indice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VNA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidoAPartirDe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia")
                        .HasDatabaseName("IX_AnbimaVNA_DataReferencia");

                    b.HasIndex("Titulo")
                        .HasDatabaseName("IX_AnbimaVNA_Titulo");

                    b.HasIndex("DataReferencia", "Titulo")
                        .IsUnique()
                        .HasDatabaseName("IX_AnbimaVNA_DataReferencia_Titulo");

                    b.ToTable("AnbimaVNAs");
                });

            modelBuilder.Entity("ArxFlow.Models.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaToolsId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodAtivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmissorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoAtivo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlphaToolsId")
                        .HasDatabaseName("IX_Ativo_AlphaToolsId");

                    b.HasIndex("CodAtivo")
                        .IsUnique()
                        .HasDatabaseName("IX_Ativo_CodAtivo");

                    b.HasIndex("EmissorId")
                        .HasDatabaseName("IX_Ativo_EmissorId");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("ArxFlow.Models.B3InstrumentoDerivativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBase")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoCfi")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoExpiracao")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoIsin")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoTipoEstrategia1")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoTipoEstrategia2")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CriterioConversao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimAvisoEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimNegocio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicioAvisoEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicioNegocio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataLimitePosicoesAbertas")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataMaturidadeAlvo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoAtivo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiasCorridos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DiasPosicaoFutura")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiasSaque")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiasUteis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstiloOpcao")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicadorConversao")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicadorPremioAntecipado")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentoFinanceiro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mercado")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoedaNegociada")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MultiplicadorContrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoBaseEstrategia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoExercicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuantidadeAtivos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Segmento")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SimboloSubjacente1")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SimboloSubjacente2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TamanhoLoteAlocacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoEntrega")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOpcao")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoValor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_B3InstrumentoDerivativo_Ativo");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("IX_B3InstrumentoDerivativo_DataVencimento");

                    b.HasIndex("InstrumentoFinanceiro", "DataReferencia")
                        .IsUnique()
                        .HasDatabaseName("IX_B3InstrumentoDerivativo_InstrumentoFinanceiro_DataReferencia");

                    b.ToTable("B3InstrumentosDerivativos");
                });

            modelBuilder.Entity("ArxFlow.Models.B3InstrumentoRendaFixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCalculo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoIF")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoIsin")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emissor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EsforcoRestrito")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Incentivada")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Indexador")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicadorOferta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentoFinanceiro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroEmissao")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PercentualIndexador")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoUnitarioEmissao")
                        .HasColumnType("TEXT");

                    b.Property<long?>("QuantidadeEmitida")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TaxaAdicional")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEmissao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Emissor")
                        .HasDatabaseName("IX_B3InstrumentoRendaFixa_Emissor");

                    b.HasIndex("InstrumentoFinanceiro")
                        .HasDatabaseName("IX_B3InstrumentoRendaFixa_InstrumentoFinanceiro");

                    b.HasIndex("Vencimento")
                        .HasDatabaseName("IX_B3InstrumentoRendaFixa_Vencimento");

                    b.HasIndex("CodigoIF", "DataReferencia")
                        .IsUnique()
                        .HasDatabaseName("IX_B3InstrumentoRendaFixa_CodigoIF_DataReferencia");

                    b.ToTable("B3InstrumentosRendaFixa");
                });

            modelBuilder.Entity("ArxFlow.Models.B3PrecoDerivativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContratosEmAberto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moeda")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoAjuste")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoAjusteAnterior")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoInicial")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoMaximo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoMedioPonderado")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoMinimo")
                        .HasColumnType("TEXT");

                    b.Property<long?>("QuantidadeNegociosRegulares")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SituacaoPrecoAjuste")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SituacaoPrecoAjusteAnterior")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxaAjuste")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxaAjusteAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UltimoPreco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia")
                        .HasDatabaseName("IX_B3PrecoDerivativo_DataReferencia");

                    b.HasIndex("Ticker", "DataReferencia")
                        .IsUnique()
                        .HasDatabaseName("IX_B3PrecoDerivativo_Ticker_DataReferencia");

                    b.ToTable("B3PrecosDerivativos");
                });

            modelBuilder.Entity("ArxFlow.Models.BcbExpectativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataReferencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DesvioPadrao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Maximo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Media")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Mediana")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Minimo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCalculo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("IX_BcbExpectativa_Data");

                    b.HasIndex("Indicador")
                        .HasDatabaseName("IX_BcbExpectativa_Indicador");

                    b.HasIndex("Data", "Indicador", "DataReferencia")
                        .IsUnique()
                        .HasDatabaseName("IX_BcbExpectativa_Data_Indicador_DataReferencia");

                    b.ToTable("BcbExpectativas");
                });

            modelBuilder.Entity("ArxFlow.Models.Boleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alocacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AtivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoletaPrincipalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContraparteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFixing")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataLiquidacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FundoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NtnbReferencia")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PU")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SpreadValor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TaxaNominal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPrecificacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId")
                        .HasDatabaseName("IX_Boleta_AtivoId");

                    b.HasIndex("BoletaPrincipalId");

                    b.HasIndex("ContraparteId")
                        .HasDatabaseName("IX_Boleta_ContraparteId");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("IX_Boleta_CriadoEm");

                    b.HasIndex("FundoId")
                        .HasDatabaseName("IX_Boleta_FundoId");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("IX_Boleta_Ticker");

                    b.ToTable("Boletas");
                });

            modelBuilder.Entity("ArxFlow.Models.Contraparte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contrapartes");
                });

            modelBuilder.Entity("ArxFlow.Models.Emissor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaToolsId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlphaToolsId")
                        .HasDatabaseName("IX_Emissor_AlphaToolsId");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Emissor_Nome");

                    b.ToTable("Emissores");
                });

            modelBuilder.Entity("ArxFlow.Models.Fundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaToolsId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlphaToolsId")
                        .HasDatabaseName("IX_Fundo_AlphaToolsId");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Fundo_Nome");

                    b.ToTable("Fundos");
                });

            modelBuilder.Entity("ArxFlow.Models.Ativo", b =>
                {
                    b.HasOne("ArxFlow.Models.Emissor", "Issuer")
                        .WithMany("Ativos")
                        .HasForeignKey("EmissorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Issuer");
                });

            modelBuilder.Entity("ArxFlow.Models.Boleta", b =>
                {
                    b.HasOne("ArxFlow.Models.Ativo", "Ativo")
                        .WithMany("Boletas")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArxFlow.Models.Boleta", "BoletaPrincipal")
                        .WithMany("BoletasLigadas")
                        .HasForeignKey("BoletaPrincipalId");

                    b.HasOne("ArxFlow.Models.Contraparte", "Contraparte")
                        .WithMany()
                        .HasForeignKey("ContraparteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArxFlow.Models.Fundo", "Fundo")
                        .WithMany("Boletas")
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ativo");

                    b.Navigation("BoletaPrincipal");

                    b.Navigation("Contraparte");

                    b.Navigation("Fundo");
                });

            modelBuilder.Entity("ArxFlow.Models.Ativo", b =>
                {
                    b.Navigation("Boletas");
                });

            modelBuilder.Entity("ArxFlow.Models.Boleta", b =>
                {
                    b.Navigation("BoletasLigadas");
                });

            modelBuilder.Entity("ArxFlow.Models.Emissor", b =>
                {
                    b.Navigation("Ativos");
                });

            modelBuilder.Entity("ArxFlow.Models.Fundo", b =>
                {
                    b.Navigation("Boletas");
                });
#pragma warning restore 612, 618
        }
    }
}
