//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator using the following command:
// xscgen --netCore --nullableReferenceAttributes --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --compactTypeNames --disableComments --debuggerStepThrough- --description- --generatedCodeAttribute- -n urn:bvmf.052.01.xsd=ArxFlow.Models.B3.Bvmf052 -n urn:bvmf.217.01.xsd=ArxFlow.Models.B3.Bvmf217 -n urn:iso:std:iso:20022:tech:xsd:head.001.001.01=ArxFlow.Models.B3.Iso20022 -o C:/Lucas/dev/hedges/HedgeManager/Models C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV000471202512300001000071934370700.xsd C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV0004712025123000010000719343707001.xsd C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV0004712025123000010000719343707002.xsd
namespace ArxFlow.Models.B3.Bvmf052
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Document", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Document", Namespace="urn:bvmf.052.01.xsd")]
    public partial class Document
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("BizFileHdr")]
        public DocumentBizFileHdr BizFileHdr { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdr", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdr
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Xchg")]
        public DocumentBizFileHdrXchg Xchg { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchg", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchg
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("BizGrpDesc")]
        public DocumentBizFileHdrXchgBizGrpDesc BizGrpDesc { get; set; }
        
        [XmlIgnoreAttribute()]
        private List<DocumentBizFileHdrXchgBizGrp> _bizGrp;
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("BizGrp")]
        public List<DocumentBizFileHdrXchgBizGrp> BizGrp
        {
            get
            {
                return _bizGrp;
            }
            set
            {
                _bizGrp = value;
            }
        }
        
        public DocumentBizFileHdrXchg()
        {
            this._bizGrp = new List<DocumentBizFileHdrXchgBizGrp>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDesc", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDesc
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Fr")]
        public DocumentBizFileHdrXchgBizGrpDescFr Fr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("To")]
        public DocumentBizFileHdrXchgBizGrpDescTo To { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("BizGrpDtls")]
        public DocumentBizFileHdrXchgBizGrpDescBizGrpDtls BizGrpDtls { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("MsgTpDef")]
        public DocumentBizFileHdrXchgBizGrpDescMsgTpDef MsgTpDef { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescFr", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescFr
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OrgId")]
        public DocumentBizFileHdrXchgBizGrpDescFrOrgId OrgId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescFrOrgId", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescFrOrgId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public DocumentBizFileHdrXchgBizGrpDescFrOrgIdId Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescFrOrgIdId", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescFrOrgIdId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OrgId")]
        public DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgId OrgId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgId", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Othr")]
        public DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgIdOthr Othr { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgIdOthr", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgIdOthr
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public string Id { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Issr")]
        public byte Issr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("SchmeNm")]
        public DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgIdOthrSchmeNm SchmeNm { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgIdOthrSchmeNm", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescFrOrgIdIdOrgIdOthrSchmeNm
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Prtry")]
        public byte Prtry { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescTo", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescTo
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OrgId")]
        public DocumentBizFileHdrXchgBizGrpDescToOrgId OrgId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescToOrgId", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescToOrgId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public DocumentBizFileHdrXchgBizGrpDescToOrgIdId Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescToOrgIdId", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescToOrgIdId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OrgId")]
        public DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgId OrgId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgId", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Othr")]
        public DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgIdOthr Othr { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgIdOthr", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgIdOthr
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public string Id { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Issr")]
        public byte Issr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("SchmeNm")]
        public DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgIdOthrSchmeNm SchmeNm { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgIdOthrSchmeNm", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescToOrgIdIdOrgIdOthrSchmeNm
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Prtry")]
        public byte Prtry { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescBizGrpDtls", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescBizGrpDtls
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("BizGrpIdr")]
        public string BizGrpIdr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("TtlNbOfMsg")]
        public ushort TtlNbOfMsg { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("BizGrpTp")]
        public string BizGrpTp { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("CreDtAndTm", DataType="dateTime")]
        public DateTime CreDtAndTm { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrpDescMsgTpDef", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrpDescMsgTpDef
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("MsgDefIdr")]
        public string MsgDefIdr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("NbOfMsg")]
        public ushort NbOfMsg { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentBizFileHdrXchgBizGrp", Namespace="urn:bvmf.052.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentBizFileHdrXchgBizGrp
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("AppHdr", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01")]
        public ArxFlow.Models.B3.Iso20022.AppHdr AppHdr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Document", Namespace="urn:bvmf.217.01.xsd")]
        public ArxFlow.Models.B3.Bvmf217.Document Document { get; set; }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator using the following command:
// xscgen --netCore --nullableReferenceAttributes --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --compactTypeNames --disableComments --debuggerStepThrough- --description- --generatedCodeAttribute- -n urn:bvmf.052.01.xsd=ArxFlow.Models.B3.Bvmf052 -n urn:bvmf.217.01.xsd=ArxFlow.Models.B3.Bvmf217 -n urn:iso:std:iso:20022:tech:xsd:head.001.001.01=ArxFlow.Models.B3.Iso20022 -o C:/Lucas/dev/hedges/HedgeManager/Models C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV000471202512300001000071934370700.xsd C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV0004712025123000010000719343707001.xsd C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV0004712025123000010000719343707002.xsd
namespace ArxFlow.Models.B3.Bvmf217
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Document", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Document", Namespace="urn:bvmf.217.01.xsd")]
    public partial class Document
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("PricRpt")]
        public DocumentPricRpt PricRpt { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRpt", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRpt
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("TradDt")]
        public DocumentPricRptTradDt TradDt { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("SctyId")]
        public DocumentPricRptSctyId SctyId { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("FinInstrmId")]
        public DocumentPricRptFinInstrmId FinInstrmId { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("TradDtls")]
        public object TradDtls { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("FinInstrmAttrbts")]
        public DocumentPricRptFinInstrmAttrbts FinInstrmAttrbts { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptTradDt", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptTradDt
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Dt", DataType="date")]
        public DateTime Dt { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptSctyId", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptSctyId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("TckrSymb")]
        public string TckrSymb { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmId", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OthrId")]
        public DocumentPricRptFinInstrmIdOthrId OthrId { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("PlcOfListg")]
        public DocumentPricRptFinInstrmIdPlcOfListg PlcOfListg { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmIdOthrId", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmIdOthrId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public ulong Id { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Tp")]
        public DocumentPricRptFinInstrmIdOthrIdTp Tp { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmIdOthrIdTp", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmIdOthrIdTp
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Prtry")]
        public byte Prtry { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmIdPlcOfListg", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmIdPlcOfListg
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("MktIdrCd")]
        public string MktIdrCd { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbts", Namespace="urn:bvmf.217.01.xsd", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbts
    {
        
        [XmlElementAttribute("OpnIntrst")]
        public uint OpnIntrst { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool OpnIntrstSpecified { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("FrstPric")]
        public DocumentPricRptFinInstrmAttrbtsFrstPric FrstPric { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("MinPric")]
        public DocumentPricRptFinInstrmAttrbtsMinPric MinPric { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("MaxPric")]
        public DocumentPricRptFinInstrmAttrbtsMaxPric MaxPric { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("TradAvrgPric")]
        public DocumentPricRptFinInstrmAttrbtsTradAvrgPric TradAvrgPric { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("LastPric")]
        public DocumentPricRptFinInstrmAttrbtsLastPric LastPric { get; set; }
        
        [XmlElementAttribute("RglrTxsQty")]
        public uint RglrTxsQty { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool RglrTxsQtySpecified { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("AdjstdQt")]
        public DocumentPricRptFinInstrmAttrbtsAdjstdQt AdjstdQt { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("AdjstdQtTax")]
        public DocumentPricRptFinInstrmAttrbtsAdjstdQtTax AdjstdQtTax { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("AdjstdQtStin")]
        public string AdjstdQtStin { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("PrvsAdjstdQt")]
        public DocumentPricRptFinInstrmAttrbtsPrvsAdjstdQt PrvsAdjstdQt { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("PrvsAdjstdQtTax")]
        public DocumentPricRptFinInstrmAttrbtsPrvsAdjstdQtTax PrvsAdjstdQtTax { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("PrvsAdjstdQtStin")]
        public string PrvsAdjstdQtStin { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsFrstPric", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsFrstPric
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsMinPric", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsMinPric
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsMaxPric", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsMaxPric
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsTradAvrgPric", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsTradAvrgPric
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsLastPric", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsLastPric
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsAdjstdQt", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsAdjstdQt
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsAdjstdQtTax", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsAdjstdQtTax
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsPrvsAdjstdQt", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsPrvsAdjstdQt
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DocumentPricRptFinInstrmAttrbtsPrvsAdjstdQtTax", Namespace="urn:bvmf.217.01.xsd")]
    [DesignerCategoryAttribute("code")]
    public partial class DocumentPricRptFinInstrmAttrbtsPrvsAdjstdQtTax
    {
        
        [XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Ccy")]
        public string Ccy { get; set; }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator using the following command:
// xscgen --netCore --nullableReferenceAttributes --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --compactTypeNames --disableComments --debuggerStepThrough- --description- --generatedCodeAttribute- -n urn:bvmf.052.01.xsd=ArxFlow.Models.B3.Bvmf052 -n urn:bvmf.217.01.xsd=ArxFlow.Models.B3.Bvmf217 -n urn:iso:std:iso:20022:tech:xsd:head.001.001.01=ArxFlow.Models.B3.Iso20022 -o C:/Lucas/dev/hedges/HedgeManager/Models C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV000471202512300001000071934370700.xsd C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV0004712025123000010000719343707001.xsd C:/Lucas/dev/hedges/schemas/BVBG.187.01_BV0004712025123000010000719343707002.xsd
namespace ArxFlow.Models.B3.Iso20022
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdr", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("AppHdr", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01")]
    public partial class AppHdr
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("BizMsgIdr")]
        public string BizMsgIdr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("MsgDefIdr")]
        public string MsgDefIdr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("CreDt", DataType="dateTime")]
        public DateTime CreDt { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Fr")]
        public AppHdrFr Fr { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("To")]
        public AppHdrTo To { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrFr", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrFr
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OrgId")]
        public AppHdrFrOrgId OrgId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrFrOrgId", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrFrOrgId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public AppHdrFrOrgIdId Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrFrOrgIdId", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrFrOrgIdId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OrgId")]
        public AppHdrFrOrgIdIdOrgId OrgId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrFrOrgIdIdOrgId", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrFrOrgIdIdOrgId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Othr")]
        public AppHdrFrOrgIdIdOrgIdOthr Othr { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrFrOrgIdIdOrgIdOthr", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrFrOrgIdIdOrgIdOthr
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public string Id { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("SchmeNm")]
        public AppHdrFrOrgIdIdOrgIdOthrSchmeNm SchmeNm { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Issr")]
        public byte Issr { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrFrOrgIdIdOrgIdOthrSchmeNm", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrFrOrgIdIdOrgIdOthrSchmeNm
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Prtry")]
        public byte Prtry { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrTo", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrTo
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OrgId")]
        public AppHdrToOrgId OrgId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrToOrgId", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrToOrgId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public AppHdrToOrgIdId Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrToOrgIdId", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrToOrgIdId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OrgId")]
        public AppHdrToOrgIdIdOrgId OrgId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrToOrgIdIdOrgId", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrToOrgIdIdOrgId
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Othr")]
        public AppHdrToOrgIdIdOrgIdOthr Othr { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrToOrgIdIdOrgIdOthr", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrToOrgIdIdOrgIdOthr
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Id")]
        public string Id { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("SchmeNm")]
        public AppHdrToOrgIdIdOrgIdOthrSchmeNm SchmeNm { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Issr")]
        public byte Issr { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AppHdrToOrgIdIdOrgIdOthrSchmeNm", Namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01", AnonymousType=true)]
    [DesignerCategoryAttribute("code")]
    public partial class AppHdrToOrgIdIdOrgIdOthrSchmeNm
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Prtry")]
        public byte Prtry { get; set; }
    }
}
